### PR TITLE
Cont patch 1

### PR DESCRIPTION
**Pull request by byang-intel**
1. support to build behind network proxy
2. optimized container build and use experience
3. fix grub-pc install issue inside container

verified on both ubuntu and mac

### CODE REVIEW

**Comment by marcelarosalesj** [comment]
Hi Bin, thanks for your PRs, this is very useful. Only a comment, could you add a verification of whether the proxies are set or not? Thanks!

**Comment by byang-intel** [comment]
Thanks for your review. I had verified it with intel internal proxy and it works on both ubuntu and Mac.

Unfortunately, I don't have machine which can access internet without proxy. I just checked the 'env' inside container if proxy is not set manually. 

I think your guys should have machines to build it without proxy. Could you please do me a favor to help verify it without proxy setting?

thanks,
Bin

**Comment by marcelarosalesj** [comment]
I used this patch without proxies and it worked fine. LGTM

**Comment by byang-intel** [comment]
thanks for your help to verify it

**Pull request merged**
